---
- hosts: all
  tasks:
    - name: remove docker
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc

    - name: install ca-certificates  curl     gnupg     lsb-release
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - ntpdate

    - name: time update
      shell: |
        ntpdate time.windows.com

    - name: 安装GPG证书
      shell: |
        curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo apt-key add -

    - name: 写入软件源信息
      shell: |
        sudo add-apt-repository "deb [arch=amd64] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable"

    - name: install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Forwarding IPv4 and letting iptables see bridged traffic
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF
        
        sudo modprobe overlay
        sudo modprobe br_netfilter
        
        # sysctl params required by setup, params persist across reboots
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF
        
        # Apply sysctl params without reboot
        sudo sysctl --system
