---
- hosts: master
  tasks:
    - name: flannel
      shell: |
        scp longhorn.tar {{ item }}:/root
        ssh {{ item }} "docker load -i longhorn.tar "

      with_items:
        - node2
        - node3
        - node4
        - node5
        - node6
